version = "6.0.0" # match the nixpkgs version of ghdl -- nix eval .#ghdl.version

[aarch64-darwin]
platform_double = "macos14-aarch64"
sha256 = "sha256-nLPMwJypXzfIi7dXs9p0Fc5e/t5R4TbgJix08/mcIkU="

[x86_64-linux]
platform_double = "ubuntu24.04-x86_64"
sha256 = "sha256-4AZM09FWnn/KJ7GGsNcegMCH3pDbTkZu133GaaV02Lw="
