name: "nix-daemon: Inject GitHub Token"
description: |
  Injects the GitHub Token into either the systemd service or launchctl daemon
  for the Nix daemon.
inputs:
  nix_cache_domain:
    description: "The https-hosted Nix build cache"
    required: true
    default: "nix-cache.fossi-foundation.org"
  nix_public_key:
    description: "The public key for the aforementioned Nix cache"
    required: true
    default: "nix-cache.fossi-foundation.org:3+K59iFwXqKsL7BNu6Guy0v+uTlwsxYQxjspXzqLYQs="
  github_token:
    description: "Optional GitHub Token to add to the Nix environment (to help avoid rate-limiting fetchers). It's heavily recommended to just use secrets.GITHUB_TOKEN in case a badly-written fetcher captures the environment somewhere (secrets.GITHUB_TOKEN is ephemeral.)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Upstream Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        # OpenLane cachix temporarily included until most things copied over
        determinate: false
        extra-conf: |
          access-tokens = github.com=${{ inputs.github_token }}
          extra-substituters = https://${{ inputs.nix_cache_domain }} https://openlane.cachix.org
          extra-trusted-public-keys = ${{ inputs.nix_public_key }} openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=
    - name: Linux -- inject GITHUB_TOKEN environment variable into nix-daemon.service
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if command -v systemctl > /dev/null; then
          systemctl list-units | grep nix-daemon
          if ! command -v crudini > /dev/null; then
            sudo apt-get install -y crudini
          fi
          sudo crudini --set /etc/systemd/system/nix-daemon.service Service Environment '"GITHUB_TOKEN=${{ inputs.github_token }}"'
          sudo systemctl daemon-reload
          sudo systemctl restart --now nix-daemon.service
        else
          echo "Not systemd. Can't do much."
        fi
    - name: macOS - inject GITHUB_TOKEN environment into org.nixos.nix-daemon.plist
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo /usr/libexec/PlistBuddy -c "Add :EnvironmentVariables:GITHUB_TOKEN string ${{ inputs.github_token }}" /Library/LaunchDaemons/org.nixos.nix-daemon.plist
        sudo launchctl bootout system/org.nixos.nix-daemon
        sudo launchctl load -w /Library/LaunchDaemons/org.nixos.nix-daemon.plist
